"""Adds Video model

Revision ID: 54abd57c2ae0
Revises: 23b1cc038721
Create Date: 2021-05-23 17:22:42.563604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54abd57c2ae0'
down_revision = '23b1cc038721'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('videos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=50), nullable=True),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('total_inventory', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('videos')
    # ### end Alembic commands ###
